#### Overview
The wireParser app is an attempt at automating the scheduling of financial wire transfer documents that are received when a bank or other financial instutition is subpoenaed. An analyst can take hours, or even days, to enter all of the data from these documents in an Excel spreadsheet for further analysis. With this tool, that scheduling happens almost instantly, which allows more time for actual analysis. 

#### How to Use the App
**First and foremost, you need to have R and RStudio installed. If you do not have these things installed, please Google how to do this. In addition, you will need to install poppler utils. You can Google "pdftotext" to find a file from which to download.**

Using this tool is very straightforward, you simply need to call the `parse_*` function that is relevant to your file and pass it the file path. Each `parse_*` function expects a certain file type(s) and will issue an error message if the wrong file type is passed. For functions that expect Excel files (i.e., `parse_citibank`, `parse_hsbc`, `parse_jpmc`), there are optional parameters such as `skip` and `sheetName` if needed. Each function makes an assumption about how many rows to skip and what the name of the relevant sheet is.  

Once the app is finished parsing the file, a `data.frame` object is returned with the relevant information from the document. In the future, I'll be looking to add a spreadsheet with every known bank geocoded, both national and international. This will allow the app to automatically geolocate any and all banks involved, which will allow the analyst to map the flow of funds. Below is the list of banks (in alphabetical order) currently accepted and how to work with each one.

#### Bank of America
Bank of America typically sends their compliance via PDFs. These files are easy for you to parse as all you need to pass is the path to the PDF file. One thing to be wary of, however, is the fact that this function relies on OCR, which means you should check to ensure all of your numbers were transcribed correctly. Aside from this, Bank of America parsing should give you little to not trouble. In addition, I have had limited samples from which to identify patterns in BoA's output. You should pay special attention to the flow of funds in the parsed output and ensure it is what you expected.

#### Capital One
Capital One sends PDF files that are very easy to parse. With the exception of OCR errors (i.e. an "l" instead of a "1"), there should be little to no errors from Capital One parsing. One thing to note is that Capital One's labels seem to be a bit off. For example, "Bene Bank" is sometimes empty whereas "Recv Bank" appears to never be blank. This implies that the true bank of the beneficiary is "Recv Bank". The logic in `parse_capone` takes this into account and sets the Beneficiary Bank and Intermediary Bank variables accordingly.

#### Citibank
Citibank sends Excel files (xls or xlsx) that are, for the most part, already parsed. The largest concern with Citibank is that at times they will leave a field blank, such as Originating Bank, as a means to imply that it is Citibank that should be in that field. The parser makes an effort to fill in the holes for you and properly identify the flow of funds. The function assumes that there is only one sheet in the workbook (if there are more than one it will read the first sheet) and that the first row of data is **not** the headers. It actually looks on line two for the variable names. It also assumes that only the first 12 columns are of value and ignores the others. 

#### HSBC
HSBC sends their files in Excel format (xls or xlsx) that are difficult to decipher. The `parse_hsbc` function makes a strong effort to properly identify all of the relelvant information and the true path of money, but it is strongly encouraged to review all output produced from this function. This function assumes that there are multiple sheets in the workbook and will look for a workbook named "Details". If it cannot find a sheet named "Details" it will ask you what the sheet name is.

#### TD Bank
TD Bank sends compliance exactly identical to Capital One. This means that `parse_tdbank` is relatively accurate when parsed. Please see the Capital One notes above for things to be aware of.

#### Shortcomings
Parsing dynamic objects is rarely perfect. There will inevitably be errors, inaccuracies, and other oddities. In this case, please file an issue via [this link](https://github.com/theRanalyst/wireParser/issues) and I will try to address the issue as soon as possible. Please note that issues you file may be difficult to address because errors cannot be reproduced with your documents due to the confidentiality. Please be patient.
